# Singleton service factory configuration/IoC injection
singletons:
- com.rayli.service.TransferService:
  - com.rayli.service.TransferServiceImpl
- com.rayli.service.BalanceService:
  - com.rayli.service.BalanceServiceImpl