# Singleton service factory configuration/IoC injection
singletons:
- com.rayli.connection.DBConnection:
  - com.rayli.connection.DBConnectionSQLite
- com.rayli.service.TransactionService:
  - com.rayli.service.TransactionServiceImpl